# Generated by Django 4.1.5 on 2023-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=25, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
