# Generated by Django 4.1.5 on 2023-01-11 14:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
    ]
