# Generated by Django 4.1.5 on 2023-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(max_length=15, verbose_name='Enter Your Contact Number..'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(choices=[('1264', '(1264) Anguilla'), ('1268', '(1268) Antigua and Barbuda'), ('1684', '(1684) American Samoa'), ('226', '(226) Burkina Faso'), ('229', '(229) Benin'), ('244', '(244) Angola'), ('257', '(257) Burundi'), ('297', '(297) Aruba'), ('32', '(32) Belgium'), ('355', '(355) Albania'), ('358', '(358) Aland Islands'), ('374', '(374) Armenia'), ('376', '(376) Andorra'), ('43', '(43) Austria'), ('54', '(54) Argentina'), ('61', '(61) Australia'), ('93', '(93) Afghanistan'), ('971', '(971) United Arab Emirates'), ('994', '(994) Azerbaijan')], default='91', max_length=40),
        ),
    ]
