# Generated by Django 4.1.5 on 2023-01-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_logo', models.ImageField(upload_to='users/%Y/%m/%d/')),
                ('channel_name', models.CharField(max_length=30)),
                ('channel_link', models.URLField()),
                ('total_subscriber', models.CharField(max_length=250)),
                ('watch_time', models.CharField(max_length=250)),
                ('adsense_approved', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=250)),
                ('channel_created_date', models.DateField(help_text='Put Date When you Started this channel.', verbose_name='Youtube Joining Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
