# Generated by Django 4.1.5 on 2023-01-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=1000)),
                ('thumbnail_imge', models.FileField(blank=True, help_text='Put Here Main Image File or Just Logo.', upload_to='channels/')),
                ('channel_name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('VlogandLifestyle', 'Vlog'), ('Education', 'Eduaction'), ('Autos & Vehicles', 'Autos & Vehicles'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Film & Animation', 'Film & Animation'), ('Gaming', 'Gaming'), ('Howto & Style', 'Howto & Style'), ('Music', 'Music'), ('News & Politics', 'News & Politics'), ('Nonprofits & Activism', 'Nonprofits & Activism'), ('People & Blogs', 'People & Blogs'), ('Pets & Animals', 'Pets & Animals'), ('Science & Technology', 'Science & Technology'), ('Sports', 'Sports'), ('Travel & Events', 'Travel & Events')], max_length=30)),
                ('channel_type', models.CharField(max_length=250)),
                ('content_type', models.CharField(blank=True, max_length=300)),
                ('audience_age', models.CharField(choices=[('13-17', '13-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64')], max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('channel_link', models.URLField()),
                ('channel_created_date', models.DateField(help_text='Put Date When you Started this channel.', verbose_name='Youtube Joining Date')),
                ('current_subscriber', models.CharField(max_length=250)),
                ('total_views', models.CharField(max_length=250)),
                ('last_views', models.CharField(help_text='Last 28Days Views', max_length=250)),
                ('real_time_views', models.CharField(blank=True, max_length=250)),
                ('active_copyright_strike', models.CharField(blank=True, max_length=300)),
                ('active_community_guidelines_strike', models.CharField(blank=True, max_length=300)),
                ('monetization_status', models.CharField(choices=[('Monetizated', 'Monetizated'), ('Non-monetized', 'Non-monetized'), ('Demontized', 'Demontized')], max_length=250)),
                ('watch_time', models.CharField(blank=True, max_length=250)),
                ('total_revenue', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='UPI/Bank Transfer/Cash/Paypal', max_length=250)),
                ('out_stock', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=True)),
                ('price', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Put Name here or Leave Blank', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='channels/reviews/')),
                ('query', models.TextField(blank=True, help_text='Max words 250 or leave blank', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='channels/imglist/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addchannel')),
            ],
        ),
    ]
