# Generated by Django 4.1.5 on 2023-01-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
