# Generated by Django 4.1.5 on 2023-01-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contactform_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='addchannel',
            name='category',
            field=models.CharField(choices=[('VlogandLifestyle', 'Vlog'), ('Education', 'Eduaction')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='addchannel',
            name='channel_created_date',
            field=models.DateField(default='', help_text='Put Date When you Started this channel.', verbose_name='Youtube Joining Date'),
        ),
        migrations.AlterField(
            model_name='addchannel',
            name='channel_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='addchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='addchannel',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addchannel',
            name='total_subscriber',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addchannel',
            name='watch_time',
            field=models.CharField(default='', max_length=250),
        ),
    ]
