# Generated by Django 4.1.5 on 2023-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_addchannel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addchannel',
            name='channel_logo',
            field=models.ImageField(upload_to='channels/'),
        ),
    ]
