# Generated by Django 4.1.5 on 2023-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_addchannel_channel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addchannel',
            name='channel_logo',
            field=models.FileField(upload_to='channels/'),
        ),
    ]
