# Generated by Django 4.1.5 on 2023-01-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_addchannel_channel_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addchannel',
            old_name='channel_logo',
            new_name='logo',
        ),
    ]
